name = "DocumentFormat"
uuid = "ffa9a821-9c82-50df-894e-fbcef3ed31cd"
ver = "0.4.0"

[deps]
CSTParser = "00ebfdb7-1f24-5e51-bd34-a7502290713f"
Tokenize = "0796e94c-ce3b-5d07-9a54-7f471281c624"

[compat]
CSTParser = "0.6"
Tokenize = "0.5.4"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
