name = "DocumentFormat"
uuid = "ffa9a821-9c82-50df-894e-fbcef3ed31cd"
version = "2.0.2-DEV"

[deps]
CSTParser = "00ebfdb7-1f24-5e51-bd34-a7502290713f"
Tokenize = "0796e94c-ce3b-5d07-9a54-7f471281c624"
FilePathsBase = "48062228-2e41-5def-b9a4-89aafe57970f"

[compat]
CSTParser = "1, 2"
FilePathsBase = "0.6, 0.7"
Tokenize = "0.5.6"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
